### ISSUE TITLE
Is this repository in active use?

### ISSUE THREAD

**Issue by cjh1** [NERSC/intro-NERSC-resources#2]
This repository doesn't seem to have been updated since 06/08/22, is it still in active use? As part of an ongoing effort to clean up the NERSC GitHub organization we are looking to archive repositories that are no longer needed. Please indicate if this repository is still in use by checking the appropriate box below.

- [ ] Still in use
- [ ] Archive

Repositories marked for archiving will be archived at the end of the year. If we don’t hear anything on this issue the default will be to archive the repository.

**Comment by helenhe40** [comment]
> * [x ]  Still in use
> * [ ]  Archive
Thanks!  Maybe revived for the next such training in the summer.

**Comment by helenhe40** [comment]
We using it now for the LBNL CS Summer Student Program 2024 now.

**Comment by helenhe40** [comment]
@cjh1 Am I not the owner or admin for this repo anymore?  Could you please revive this so I can MR my pull request?  Thanks!

**Comment by cjh1** [comment]
@helenhe40 I didn't archive this one, as requested, you should be good to merge the PR. It you don't have permission I can fix that.

**Comment by cjh1** [comment]
@helenhe40 I have made you the admin for the repo, you should now have the permissions.

**Comment by helenhe40** [comment]
Thanks Chris!  I confirm that I can now commit to the main branch directly.

**Comment by cjh1** [comment]
Great, I am going to go  ahead and close this issue.
